spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userdata_db
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update

#spring.jpa.show-sql=true